// Copyright 2026 Erst Users
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"bufio"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderGuidedErstTomlIncludesCommentsAndFailoverURLs(t *testing.T) {
	content := renderGuidedErstToml(guidedConfigOptions{
		Network:   "public",
		RPCURLs:   []string{"https://rpc-a.example.com", "https://rpc-b.example.com"},
		CachePath: ".erst/cache",
	})

	assert.Contains(t, content, "# Erst configuration generated by `erst config init`")
	assert.Contains(t, content, `rpc_url = "https://rpc-a.example.com"`)
	assert.Contains(t, content, `rpc_urls = ["https://rpc-a.example.com", "https://rpc-b.example.com"]`)
	assert.Contains(t, content, `network = "public"`)
	assert.Contains(t, content, `network_passphrase = "Public Global Stellar Network ; September 2015"`)
	assert.Contains(t, content, `cache_path = ".erst/cache"`)
}

func TestRunConfigWizardUsesDetectedRPCs(t *testing.T) {
	original := detectRecommendedRPCsFunc
	detectRecommendedRPCsFunc = func(ctx context.Context, network string) ([]string, error) {
		_ = ctx
		_ = network
		return []string{"https://fast.example.com", "https://slow.example.com"}, nil
	}
	defer func() {
		detectRecommendedRPCsFunc = original
	}()

	opts := guidedConfigOptions{
		Network:   "testnet",
		CachePath: ".erst/cache",
	}

	var out bytes.Buffer
	cmd := &cobraTestCommand{out: &out, in: strings.NewReader("\n\n\n")}

	err := runConfigWizard(cmd.command(), &opts)
	require.NoError(t, err)
	assert.Equal(t, "testnet", opts.Network)
	assert.Equal(t, []string{"https://fast.example.com", "https://slow.example.com"}, opts.RPCURLs)
	assert.Equal(t, ".erst/cache", opts.CachePath)
	assert.Contains(t, out.String(), "RPC URLs (comma-separated) [https://fast.example.com, https://slow.example.com]: ")
}

func TestRunConfigInitWritesConfigAndCreatesCacheDir(t *testing.T) {
	root := t.TempDir()
	outputPath := filepath.Join(root, "erst.toml")

	opts := guidedConfigOptions{
		Force:       false,
		Interactive: false,
		OutputPath:  outputPath,
		Network:     "testnet",
		RPCURLs:     []string{"https://recommended.example.com"},
		CachePath:   ".erst/cache",
	}

	var out bytes.Buffer
	cmd := &cobraTestCommand{out: &out, in: strings.NewReader("\n\n\n")}

	err := runConfigInitWithOptions(cmd.command(), opts)
	require.NoError(t, err)

	content, readErr := os.ReadFile(outputPath)
	require.NoError(t, readErr)
	assert.Contains(t, string(content), `rpc_url = "https://recommended.example.com"`)
	assert.DirExists(t, filepath.Join(root, ".erst", "cache"))
	assert.Contains(t, out.String(), "Generated ")
}

func TestPromptNetworkRejectsInvalidValue(t *testing.T) {
	reader := bufio.NewReader(strings.NewReader("invalid\n"))
	out := &bytes.Buffer{}

	_, err := promptNetwork(reader, out, "testnet")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "invalid network")
}

type cobraTestCommand struct {
	out *bytes.Buffer
	in  *strings.Reader
}

func (c *cobraTestCommand) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.SetOut(c.out)
	cmd.SetErr(c.out)
	cmd.SetIn(c.in)
	return cmd
}
